### ISSUE TITLE
Are online CDDT and GPU CDDT usable?

### ISSUE THREAD

**Issue by xlicz** [kctess5/range_libc#2]
Hi, 

Thank you for develop this cool algorithm and open source it!
I found online CDDT and GPU CDDT available in the develop2 branch, are they usable?

Bests

**Comment by kctess5** [comment]
Sorry for slow reply. Yes they are usable, but I haven't had much time to do some cleanup and integration with the master branch. I'm hoping to do this some time soon.

The online CDDT thing works well, but in my experience, the GPU version is not significantly faster than the CPU version. I think this is because the memory access pattern does not play nicely with the GPU.

**Comment by xlicz** [comment]
close #2
Thanks for your nice reply.

**Comment by xlicz** [comment]
Thanks for your nice reply.
